[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "raider_backend"
version = "0.0.1"
description = "Autonomous Software Development"
readme = "README.md"
requires-python = ">=3.9,<3.13"
dependencies = []

[project.optional-dependencies]

[project.urls]
homepage = "https://github.com/sikfeng/raider-backend"
repository = "https://github.com/sikfeng/raider-backend"

[project.scripts]
init_repo_agent = "raider_backend.repo_agent:main"
launch_endpoint = "raider_backend.launch:main"

[tool.setuptools.packages.find]
where = ["."]