[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "aider_agent"
version = "0.0.1"
description = "Autonomous Software Development"
readme = "README.md"
requires-python = ">=3.9,<3.13"
dependencies = []

[project.optional-dependencies]

[project.urls]
homepage = "https://github.com/sikfeng/aider-agent"
repository = "https://github.com/sikfeng/aider-agent"

[project.scripts]
init_repo_agent = "aider_agent.repo_agent:main"
launch_endpoint = "aider_agent.launch:main"

[tool.setuptools.packages.find]
where = ["."]