name: raider-backend
services:
  workspace:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file: .env
    volumes: 
      - ../..:/workspace
    command: sleep infinity

  db:
    image: neo4j:5.23.0
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - neo4j-data:/data

volumes:
  neo4j-data: